image: Visual Studio 2022

version: 3.1.{build}
build: off
test: off

init:
  - git config --global core.autocrlf true

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  - msbuild ResxFormatter\ResxFormatter.csproj /restore /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_build:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
