image: Visual Studio 2026

version: 4.0.{build}

# Required for non-PR Gallery publication; configure
# VSIX_GALLERY_MANAGE_TOKEN as a secure project environment variable.

build: off
test: off

init:
  - git config --global core.autocrlf true

build_script:
  - appveyor-build.cmd
