// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResxFormatter
{
    internal sealed partial class Vsix
    {
        public const string Id = "ResxFormatter.61507132-4401-47b1-9950-575e43b964c6";
        public const string Name = "ResxFormatter";
        public const string Description = @"Formats .resx files: Sorts data entries by name and removes xml comments.";
        public const string Language = "en-US";
        public const string Version = "0.9";
        public const string Author = "Stefan Egli";
        public const string Tags = "resources, resx, formatting";
    }
}
