// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResxFormatter.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidResxFormatterPackageString = "40d1f52e-e828-4cca-8279-df4ccd348f09";
        public static Guid guidResxFormatterPackage = new Guid(guidResxFormatterPackageString);

        public const string guidResxFormatterPackageCmdSetString = "c7e059c9-69b5-443d-88f4-930c6a3975ca";
        public static Guid guidResxFormatterPackageCmdSet = new Guid(guidResxFormatterPackageCmdSetString);

        public const string guidImagesString = "96694352-566d-419c-a983-946498938249";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FormatAllCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}