// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResxFormatter.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidResxFormatterPackageString = "40d1f52e-e828-4cca-8279-df4ccd348f09";
        public static Guid guidResxFormatterPackage = new Guid(guidResxFormatterPackageString);

        public const string guidResxFormatterPackageTopMenuCmdSetString = "056b1778-6320-485b-8e99-ed6f2e1cbf30";
        public static Guid guidResxFormatterPackageTopMenuCmdSet = new Guid(guidResxFormatterPackageTopMenuCmdSetString);

        public const string guidResxFormatterPackageCmdSetString = "c7e059c9-69b5-443d-88f4-930c6a3975ca";
        public static Guid guidResxFormatterPackageCmdSet = new Guid(guidResxFormatterPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ResxFormatterTopMenu = 0x1020;
        public const int ResxFormatterTopMenu1 = 0x1020;
        public const int ResxFormatterCommands = 0x1021;
        public const int FormatAllCommandId = 0x0100;
    }
}